services:
  redis:
    image: redis:latest
    command: redis-server --requirepass ${DB_REDIS_PASSWORD}
    ports:
      - "${DB_REDIS_PORT}:6379"
    environment:
      REDIS_PASSWORD: ${DB_REDIS_PASSWORD}
      REDIS_DISABLE_COMMANDS: "FLUSHDB,FLUSHALL"
      REDIS_DATABASES: 16
      REDIS_PORT: ${DB_REDIS_PORT}
    volumes:
      - ./data:/data
    container_name: dexbooru-redis
