version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "${DB_REDIS_PORT}:${DB_REDIS_PORT}"
    environment:
      REDIS_HOST: ${DB_REDIS_HOST}
      REDIS_USER: ${DB_REDIS_USER}
      REDIS_PASSWORD: ${DB_REDIS_PASSWORD}
      REDIS_DISABLE_COMMANDS: "FLUSHDB,FLUSHALL"
    volumes:
      - ./data:/data
    container_name: dexbooru-redis
