export const IMAGE_TO_SCREEN_RATIO_THRESHOLD = 0.8;
export const POST_IMAGE_FALLBACK_WIDTH = 250;
export const POST_IMAGE_FALLBACK_HEIGHT = 250;
export const POST_COLLECTION_IMAGE_FALLBACK_WIDTH = 300;
export const POST_COLLECTION_IMAGE_FALLBACK_HEIGHT = 300;

export const PROFILE_PICTURE_CROP_UI_SIZE = 400;
export const PROFILE_PICTURE_CROP_EXPORT_SIZE = 256;
export const PROFILE_PICTURE_CROP_ZOOM_MIN = 0.5;
export const PROFILE_PICTURE_CROP_ZOOM_MAX = 3;
export const PROFILE_PICTURE_CROP_ZOOM_STEP = 0.1;
export const PROFILE_PICTURE_CROP_ZOOM_WHEEL_DELTA = 0.1;
export const PROFILE_PICTURE_CROP_PNG_QUALITY = 0.95;
