export const IMAGE_TO_SCREEN_RATIO_THRESHOLD = 0.8;
export const POST_IMAGE_FALLBACK_WIDTH = 250;
export const POST_IMAGE_FALLBACK_HEIGHT = 250;
export const POST_COLLECTION_IMAGE_FALLBACK_WIDTH = 300;
export const POST_COLLECTION_IMAGE_FALLBACK_HEIGHT = 300;
