export const AWS_DEFAULT_REGION = process.env.AWS_DEFAULT_REGION || 'us-west-2';
export const AWS_CLOUDFRONT_POSTS_BASE_URL = process.env.AWS_CLOUDFRONT_POSTS_BASE_URL || '';
export const AWS_CLOUDFRONT_PROFILE_PICTURE_BASE_URL = process.env.AWS_CLOUDFRONT_PROFILE_PICTURE_BASE_URL || '';
export const AWS_PROFILE_PICTURE_BUCKET_NAME = process.env.AWS_PROFILE_PICTURE_BUCKET_NAME || '';
export const AWS_POST_PICTURE_BUCKET_NAME = process.env.AWS_POST_PICTURE_BUCKET_NAME || '';
