export const SINGLE_POST_CACHE_TIME_SECONDS = 60;
export const SINGLE_USER_CACHE_TIME_SECONDS = 30;
export const TAGS_PAGINATION_CACHE_TIME_SECONDS = 30;
export const ARTISTS_PAGINATION_CACHE_TIME_SECONDS = 30;
