export const MAXIMUM_COLLECTION_DESCRIPTION_LENGTH = 250;
export const MAXIMUM_COLLECTION_TITLE_LENGTH = 100;
export const MAXIMUM_POSTS_PER_COLLECTION = 15;
export const MAXIMUM_COLLECTIONS_PER_PAGE = 28;
export const COLLECTION_TITLE_PREVIEW_LENGTH = 35;
export const COLLECTION_TITLE_UPDATE_MODAL_MAX_LENGTH = 15;
export const COLLECTION_DESCRIPTION_PREVIEW_LENGTH = 50;
