export const MAXIMUM_CONTENT_LENGTH = 1500;
export const MAXIMUM_COMMENTS_PER_PAGE = 35;
export const COMMENT_TEXT_AREA_ROWS = 5;
export const COMMENT_CONTENT_PREVIEW_LENGTH = 120;
export const COMMENT_CONTENT_PREVIEW_ELLIPSIS = '...';
